# Generated by Django 4.0 on 2024-01-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(db_column='email', max_length=255, unique=True)),
                ('username', models.CharField(db_column='username', max_length=255)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('phone', models.CharField(db_column='phone', max_length=255)),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('is_admin', models.BooleanField(db_column='is_admin', default=False)),
                ('avatar', models.CharField(db_column='avatar', default='default.jpg', max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('access_token', models.CharField(db_column='access_token', max_length=500, unique=True)),
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='session', serialize=False, to='users.user')),
            ],
            options={
                'db_table': 'user_session',
                'managed': True,
            },
        ),
    ]
