# Generated by Django 4.0 on 2024-01-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='id_user',
            new_name='user',
        ),
    ]
