# Generated by Django 4.0 on 2024-02-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersession_created_at_usersession_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='updated_at',
        ),
    ]
