# Generated by Django 4.0 on 2024-02-02 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usersession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
    ]
