# Generated by Django 4.0 on 2024-01-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=500)),
                ('image', models.CharField(db_column='image', default='category_default.jpg', max_length=500)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
    ]
